name: Bug Report
description: Report a bug or pipeline execution issue
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide pipeline details to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: "Example: Quality gate fails with 'all_pass' but individual evaluators show passing scores"
    validations:
      required: true

  - type: textarea
    id: pipeline_yaml
    attributes:
      label: Pipeline YAML
      description: Provide your pipeline definition
      placeholder: |
        name: customer_sentiment
        version: 1.0.0
        
        extract:
          source: data.csv
          format: csv
        
        transform:
          prompt: prompts/sentiment.txt
          model: gpt-4o-mini
        
        evaluate:
          evaluators:
            - type: semantic
              threshold: 0.8
          quality_gate: all_pass
        
        load:
          destination: output.csv
      render: yaml
    validations:
      required: true

  - type: dropdown
    id: stage
    attributes:
      label: Stage Where Error Occurred
      description: Which pipeline stage failed?
      options:
        - Extract
        - Transform
        - Evaluate
        - Load
        - Quality Gate
        - Pipeline Runner
        - Other
    validations:
      required: true

  - type: dropdown
    id: data_format
    attributes:
      label: Data Format
      description: What data format are you using?
      options:
        - CSV
        - JSON
        - JSONL
        - Parquet
        - Other

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "Example: All records should pass quality gate with scores >0.8"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages and quarantine logs
      placeholder: |
        Error: QualityGateError: 15/100 records failed quality gate
        
        Quarantine log (first failed record):
        Record ID: 42
        Evaluator: semantic
        Score: 0.75 (threshold: 0.8)
        Failure reason: Score below threshold
      render: shell

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal Reproduction
      description: Provide minimal data and steps to reproduce
      placeholder: |
        # data.csv (5 rows)
        text,reference
        "Paris is capital","Paris is the capital of France"
        
        # Run command
        loom run customer_sentiment.yaml
      render: text
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      value: |
        - Loom version: 
        - Python version: 
        - OS: 
        - Arbiter version: 
        - LLM provider: 
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: "Example: Only happens with large files (>1000 records)"
